version = 1

test_patterns = [
    "test/**",
    "test_*.py"
]

[[analyzers]]
name = "python"
enabled = true
dependency_file_paths = ["requirements-dev.txt", "setup.py"]

    [analyzers.meta]
    runtime_version = "3.x.x"
